sudo: required
dist: trusty

language:
  - java

jdk:
  - oraclejdk8  # Building Bazel requires JDK8.

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg'
      - sourceline: 'deb https://deb.nodesource.com/node_7.x trusty main'
        key_url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    packages:
      - bazel
      - python3-six
      - nodejs

before_script:
  - pwd
  - ls -la
  - java -version
  - sudo "cd /usr/local; npm install mocha"


-jobs:
  include:
    - stage: test
      script: tools/docker/test_all.sh
 
