sudo: required
dist: trusty

language:
  - java

jdk:
  - oraclejdk8  # Building Bazel requires JDK8.

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg'
      - sourceline: 'deb https://deb.nodesource.com/node_7.x trusty main'
        key_url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    packages:
      - bazel
      - python3-six
      - nodejs

before_script:
  - pwd
  - ls -la
  - java -version
  - cd /usr/local
  - sudo npm install mocha
  - ls -l
  - find . -path "*mocha/bin"
  - cd -
  - ls -l

cache:
  directories:
    - $HOME/.cache/bazel

jobs:
  include:
    - stage: bazel test
      script: PATH=/usr/local/node_modules/mocha/bin:$PATH  bazel test --force_python py3 --python_path /usr/bin/python3 --test_output=errors --verbose_failures  ...
      script: ls -la $HOME
