language: java

before_script:
  - pwd
  - ls -la
  - java -version
  - wget https://hblok.net/bazel
  - echo "4169f408933f188003c02d8e657d5027  bazel" > bazel.md5
  - md5sum -c bazel.md5
  - chmod 700 bazel

jobs:
  include:
    - stage: test
      script: ./bazel test ...
