
# This depends on the maven2 repository, and specifically the
# "org.apache.commons:commons-collections4:4.4" artifact specified in MODULE.bazel.
java_test(
    name = "CollectionsTest",
    srcs = ["CollectionsTest.java"],
    deps = [
        "@maven2//:org_apache_commons_commons_collections4"
    ]
)
