java_test(
   name = "InfoProviderTest",
   srcs = ["InfoProviderTest.java"],
   deps = ["//java/com/example/info"],
   test_class = "com.example.info.InfoProviderTest",
)

java_test(
    name = "HelloJunitTest",
    srcs = ["HelloJunitTest.java"],
    test_class = "com.example.HelloJunitTest",
 )
 