java_test(
   name = "InfoProviderTest",
   srcs = ["InfoProviderTest.java"],
   deps = ["//java/com/example/info"],
)

java_test(
    name = "HelloJunitTest",
    srcs = ["HelloJunitTest.java"],
 )
 