name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      
      - name: Install
        run: sudo apt-get install -y mocha nodejs python3-dev python-dev
      
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
        
      - name: List
        run: |
            ls ${{ github.workspace }}
            cat /etc/issue

      - run: bazel test --test_output all ...

